Repository today-fridge/today-fridge, pull requests merged in 2025-09, with the labels that each got.

#8 [TF-42, TF-46] 코드 재사용성 향상 및 데이터 페칭 최적화
  app/layout.tsx
  app/recipes/[id]/page.tsx
  app/recipes/page.tsx
  app/recipes/search/AllRecipesClient.tsx
  app/recipes/search/page.tsx
  components/AppProvider.tsx
  components/IngredientConsumptionModal.tsx
  components/RecipeCard.tsx
  hooks/useRecipeQuery.ts
  lib/recipeTransform.ts
  package.json
  pnpm-lock.yaml
  services/recipes.ts
  types/index.ts
Labels: 🎨 Design, 🔨 Refactor

#11 [TF-52]: 내 기록 페이지 Next.js 마이그레이션
  app/records/page.tsx
  components/MyRecordsScreen.tsx
  components/WebHeader.tsx
Labels: ✨ Feature

#10 [TF-50] 유통기한 표기방식 수정
  components/FridgeScreen.tsx
  types/index.ts
Labels: 🔨 Refactor

#14 [TF-38] 로그인 페이지 UI 구현
  app/(auth)/login/page.tsx
  components/WebHeader.tsx
  public/login/btnGoogle.svg
  public/login/btnKakao.svg
Labels: 🎨 Design

#13 [TF-31] favicon 및 title 변경
  app/favicon.ico
  app/layout.tsx
  public/favicon.png
Labels: 🎨 Design

#17 [TF-47, TF-65] 배포 시 오류 사항 수정, UI 문제 수정
  app/recipes/[id]/RecipeDetailClient.tsx
  components/CookingCompleteModal.tsx
  components/RecipeCard.tsx
Labels: 🌏 Deploy, 🎨 Design, 🐞 BugFix

#20 [TF-65] 냉장고 재료관리 빌드 오류 수정
  app/api/ingredients/[id]/route.ts
  app/api/ingredients/route.ts
  app/api/ocr/route.ts
  app/page.tsx
  components/AddIngredientModal.tsx
  components/FridgeScreen.tsx
  hooks/useIngredientQuery.ts
  types/index.ts
Labels: 🌏 Deploy, 🐞 BugFix

#21 [TF-36] 랜딩페이지 UI 구현
  app/home/page.tsx
  components/ui/badge.tsx
Labels: 🎨 Design

#28 [TF-61] 사용자 별 냉장고 재료를 관리 하기 위한 수정
  app/(auth)/login/callback/page.tsx
  app/(auth)/login/page.tsx
  app/api/ingredients/[id]/route.ts
  app/api/ingredients/route.ts
  app/api/users/route.ts
  components/AppProvider.tsx
  components/AuthProvider.tsx
  components/NavLoginButton.tsx
  config/supabase.js
  lib/supabase/client.ts
  lib/supabase/middleware.ts
  lib/supabase/server.ts
  middleware.ts
  package.json
  pnpm-lock.yaml
  prisma/schema.prisma
Labels: ✨ Feature, 🔨 Refactor

#29 [TF-68] 소개 페이지 추가 및 UI 개선
  app/(auth)/login/callback/page.tsx
  app/(auth)/login/page.tsx
  app/intro/page.tsx
  app/recipes/page.tsx
  components/FridgeScreen.tsx
  components/RecipeCard.tsx
  components/WebHeader.tsx
  public/favicon.png
Labels: 🎨 Design

#31 [TF-73]내 기록 페이지 데이터베이스 연동
  app/api/cooking-records/route.ts
  app/recipes/[id]/RecipeDetailClient.tsx
  app/records/page.tsx
  components/CookingCompleteModal.tsx
  hooks/useCookingRecordsQuery.ts
  prisma/schema.prisma
  services/cookingRecords.ts
Labels: ✨ Feature, 🎨 Design

#32 [TF-59] 요리 완성 기능 구현 및 재료 차감 로직 추가
  app/api/cooking-complete/route.ts
  app/recipes/[id]/InventoryStatus.tsx
  app/recipes/[id]/RecipeDetailClient.tsx
  components/CookingCompleteModal.tsx
  hooks/useRecipeQuery.ts
  lib/recipeTransform.ts
  lib/supabase/middleware.ts
  services/recipes.ts
Labels: ✨ Feature, 📬 API, 🐞 BugFix

#33 [TF-54]OCR 다중 추출된 데이터 개별추가 기능 UI및 로직 추가
  app/records/page.tsx
  components/AddIngredientModal.tsx
  components/ReceiptScanner.tsx
Labels: ✨ Feature, 🎨 Design
